In [3]:
#Installing modules
!pip install gensim
!pip install nltk

Requirement already satisfied: gensim in c:\users\harsh123\anaconda3\lib\site-packages (4.1.2)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\harsh123\anaconda3\lib\site-packages (from gensim) (3.0.0)
Requirement already satisfied: Cython==0.29.23 in c:\users\harsh123\anaconda3\lib\site-packages (from gensim) (0.29.23)
Requirement already satisfied: scipy>=0.18.1 in c:\users\harsh123\anaconda3\lib\site-packages (from gensim) (1.6.2)
Requirement already satisfied: numpy>=1.17.0 in c:\users\harsh123\anaconda3\lib\site-packages (from gensim) (1.20.1)
Requirement already satisfied: requests in c:\users\harsh123\anaconda3\lib\site-packages (from smart-open>=1.8.1->gensim) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\harsh123\anaconda3\lib\site-packages (from requests->smart-open>=1.8.1->gensim) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\harsh123\anaconda3\lib\site-packages (from requests->smart-open>=1.8.1->gensim) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\harsh123\anaconda3\lib\site-packages (from requests->smart-open>=1.8.1->gensim) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\harsh123\anaconda3\lib\site-packages (from requests->smart-open>=1.8.1->gensim) (4.0.0)
Requirement already satisfied: nltk in c:\users\harsh123\anaconda3\lib\site-packages (3.6.1)
Requirement already satisfied: tqdm in c:\users\harsh123\anaconda3\lib\site-packages (from nltk) (4.59.0)
Requirement already satisfied: click in c:\users\harsh123\anaconda3\lib\site-packages (from nltk) (7.1.2)
Requirement already satisfied: regex in c:\users\harsh123\anaconda3\lib\site-packages (from nltk) (2021.4.4)
Requirement already satisfied: joblib in c:\users\harsh123\anaconda3\lib\site-packages (from nltk) (1.0.1)

In [5]:
#Importing libraries
from nltk.tokenize import sent_tokenize, word_tokenize
import nltk
nltk.download('punkt')
import gensim
from gensim.models import Word2Vec

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Harsh123\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [7]:
import pandas as pd
rev = pd.read_csv(r"bank_train.csv")
rev.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,76,retired,married,secondary,no,2302.0,no,no,telephone,5,feb,110,1,87,2,failure,no
1,66,retired,divorced,unknown,no,53.0,no,no,cellular,12,jul,562,4,-1,0,unknown,yes
2,51,management,married,tertiary,no,2455.0,yes,no,cellular,21,jul,553,1,-1,0,unknown,yes
3,41,blue-collar,married,secondary,no,356.0,yes,no,cellular,14,may,90,5,-1,0,unknown,no
4,51,technician,married,secondary,no,-1944.0,yes,no,cellular,7,may,623,1,-1,0,unknown,yes

In [14]:
#Building the corpus
corpus_text = 'n'.join(rev[:1000]['education'])
data = []
# iterate through each sentence in the file
for i in sent_tokenize(corpus_text):
    temp = []
    # tokenize the sentence into words
    for j in word_tokenize(i):
        temp.append(j.lower())
    data.append(temp)

In [15]:
#Create the word embeddings using CBOW architecture or Skip Gram architecture
model1 = gensim.models.Word2Vec(data, min_count = 1, window = 5, sg=0) 
model2 = gensim.models.Word2Vec(data, min_count = 1, window = 5, sg =1)